### PR TITLE
Run ktlint against all *.kt files

### PR DESCRIPTION
**Pull request by kzys**
It sometimes looks odd, but getting rid of all style discussion from PRs is good, I think.

### CODE REVIEW

**Comment by karino2** [comment]
I don't agree many changes of this PR are correct.
Why you think this can avoid style related discussion? (like my comment now)

For me, it seems this is too much for just this size of project.

But I'm not so much against, either.
If you think you have good reason to merge this PR, I want to hear that.

What make you create this PR?

**Comment by kzys** [comment]
Sorry. I probably should have discussed at #79 first.

I'd like to 1) make our style consistent, while 2) not spending too much time on pull requests to ask others to align the place of `{`.

Auto-formatting tools such as ktlint work well, while the result may not look great all the time. I think "does it look great?" is subjective, while "does it look consistent" is objective. Personally I'm okay to compromise the former a bit to achieve the latter with ease.

What do you think?

**Comment by karino2** [comment]
Why you want to  make style consistent?
If developer write code with the same IDE, I think the result is already reasonably consistent.
For me, the variation of differences like that this PR adress are 100 percent OK.

Do you think current variation of style is too much?
For example, which style rules of this PR do you want to make consistent?
If it is not so much, I feel this style  check is more harm than benefit.
But if you care much about these kind of styles and the consistency of this level make your daily development really happy,  we have enough reason to keep this level of consistency (though for me, there is no benefit and it just add tiny extra development cost).

**Comment by karino2** [comment]
By the way, how to create these change after this PR?

1. by hand (tool just does check, no formating)
2. run some format tool by hand
3. CI add entra commit for style fix automatically

If 3, I'm OK (but we need to grant more permission to CI, right?).
For 2, it depends on speed, but it might be OK.
For 1, we need some consensus before merging this PR.

**Comment by kzys** [comment]
It is 2. It roughly takes 5 seconds on my MacBook right now.

```
% time ./gradlew format

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed
./gradlew format  1.04s user 0.15s system 21% cpu 5.604 total
```

Regarding consistency, the projects I have worked on usually have these style rules and don't know how it goes without enforcing them. I'm fine if you want to keep things as is.

**Comment by karino2** [comment]
OK, if you dont't know the benefit, I reject this PR.

**Pull request closed without merging**
