### PR TITLE
Install Android Emulator beforehand to run instrumented tests

### PR DESCRIPTION
**Pull request by kzys**
Sorry. #81 was still work-in-progress. Please merge this change *after* Travis is becoming green.

### CODE REVIEW

**Comment by karino2** [comment]
Sorry.
Could you add comment here when it's ready?

**Comment by kzys** [comment]
Sure. Will do.

**Comment by kzys** [comment]
@karino2 Finally it is ready to merge!

**Comment by karino2** [comment]
I couldn't figure out what installation script does.
But I think if it works properly anyway, it's enough.
Merge.

**Pull request merged**
