### PR TITLE
Add ktlint

### PR DESCRIPTION
**Pull request by kzys**

### CODE REVIEW

**Comment by karino2** [comment]
How to evaluate this PR?
Just building cause no message. How to run ktlint?

**Comment by kzys** [comment]
Probably enabling Travis CI is the easiest path. You can go https://travis-ci.org/account/repositories to add karino2/kotlitex on your Travis account.

Meanwhile, I will rebase and update the CR to have .travis.yml on this branch.

**Comment by karino2** [comment]
I check the result and I agree that rule is reasonable even in our special circumstance.
So I think we should merge this PR.
But some of the warning (like not using parameter, if sentence is always true) is not because something is wrong but because porting is still on going.
I think it's difficult to be "remove all the warning at first, then keep warning zero for further development".
Suppress all warning by hand is just slow down porting and does not give so much benefit in this case.

Do you think it's OK to stay some warning exist while merge this pull request?

**Comment by kzys** [comment]
Yep. It is totally fine to keep the warnings at this stage.

**Comment by karino2** [comment]
OK. merged.

**Pull request merged**
